interface/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^accounts/login/$', 'main.views.login', name='login-url'),
    url(r'^', include('main.urls', namespace="oauth2")),
    url(r'^admin/', include(admin.site.urls)),
]

main/urls.py
from django.conf.urls import url, patterns
from .views import *

urlpatterns = patterns('',
                       url(r'^$', index, name='index'),
                       url(r'^oauth2callback', auth_return, name='return'),
                       url(r'^add_product/$', add_product, name='add'),
                       )

templates/add_product.html
{% load bootstrap3 %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    <style>
        footer {
              position: relative;
              bottom: 0;
              width: 100%;
              border-top: solid 1px gray;
              /* Set the fixed height of the footer here */
              height: 50px;
        }
    </style>

    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    {% bootstrap_javascript %}
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Google Shopping Interface</a>
    </div>
      <ul class="nav navbar-nav">
      <li class="divider"></li>
      <li><a href="{% url 'oauth2:index' %}">Update product</a></li>
      <li><a href="{% url 'oauth2:add' %}">Add product</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
          <li class="divider"></li>
          <li><a>Merchant ID: {{ merchant_id }}</a></li>
      </ul>

  </div><!-- /.container-fluid -->
</nav>
<div class="container">
<div class="row">
    {% if messages %}
    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
{% endif %}
<div class="col-md-3 col-md-offset-1">
<legend>Add product</legend>
<form method="post" action="">
    {% csrf_token %}
    <div class="form-group">
        <label for="offerId">Offer ID</label>
        {{ form.offerId|attr:"class:form-control" }}
    </div>
    <div class="form-group">
        <label for="title">Title</label>
        {{ form.title|attr:"class:form-control" }}
    </div>
    <div class="form-group">
        <label for="description">Description</label>
        {{ form.description|attr:"class:form-control" }}
    </div>
    <div class="form-group">
        <label for="productType">Product type</label>
        {{ form.productType|attr:"class:form-control"|attr:"placeholder: example: Automobile parts" }}
    </div>
    <div class="form-group">
        <label for="condition">Condition</label>
        {{ form.condition|attr:"class:form-control" }}
    </div>
    <div class="form-group">
        <label for="availability">Availability</label>
        {{ form.availability|attr:"class:form-control" }}
    </div>
    <div class="form-group">
        <label for="price">Price</label>
        {{ form.price|attr:"class:form-control"|attr:"placeholder: example: 19.95" }}
    </div>
    <div class="form-group">
        <label for="currency">Currency</label>
        {{ form.currency|attr:"class:form-control" }}
    </div>
</div>
<div class="col-md-3">
    <div class="form-group">
        <label for="brand">Brand</label>
        {{ form.brand|attr:"class:form-control"|attr:"placeholder: example: Sunpro" }}
    </div>
    <div class="form-group">
        <label for="gtin">GTIN(Global Trade Item Number)</label>
        {{ form.gtin|attr:"class:form-control"|attr:"placeholder: example: 012345678905" }}
    </div>
    <div class="form-group">
        <label for="mpn">MPN(Manufacturer Part Number)</label>
        {{ form.mpn|attr:"class:form-control"|attr:"placeholder: example: HSC0424PP" }}
    </div>
    <div class="form-group">
        <label for="link">Product link</label>
        {{ form.link|attr:"class:form-control"|attr:"placeholder: example: http://eg.com" }}
    </div>
    <div class="form-group">
        <label for="imageLink">Image Link</label>
        {{ form.imageLink|attr:"class:form-control"|attr:"placeholder: example: http://eg.com/sample.png" }}
    </div>
    <div class="form-group">
        <label for="shippingPrice">Shipping price</label>
        {{ form.shippingPrice|attr:"class:form-control"|attr:"placeholder: example: 2.99" }}
    </div>
    <div class="form-group">
        <label for="shippingCurrency">Shipping currency</label>
        {{ form.shippingCurrency|attr:"class:form-control" }}
    </div>
    <div class="form-group">
        <label for="taxRate">Tax rate</label>
        {{ form.taxRate|attr:"class:form-control"|attr:"placeholder: example: 0.16" }}
    </div>
    <div class="form-group">
        <label for="taxLocation">Tax location ZIP code</label>
        {{ form.taxLocation|attr:"class:form-control"|attr:"placeholder: example: 20505" }}
    </div>
    <div class="form-group">
        <label for="taxRegion">Tax region</label>
        {{ form.taxRegion|attr:"class:form-control"|attr:"placeholder: example: FL, NJ" }}
    </div>
    <div class="form-group">
        <label for="taxShipping">Tax on shipping cost</label>
        {{ form.taxShipping|attr:"class:form-control" }}
    </div>
    <div class="form-group">
        <button class="btn btn-small btn-success" type="submit">Add product</button>
    </div>

</div>
</form>
</div>
</div>
<footer class="footer">
      <div class="container">
        <p class="text-muted">Place footer content here.</p>
      </div>
</footer>
</body>
</html>

templates/index.html
{% load bootstrap3 %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    <style>
        footer {
              position: absolute;
              bottom: 0;
              width: 100%;
              border-top: solid 1px gray;
              /* Set the fixed height of the footer here */
              height: 50px;
        }
    </style>

    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    {% bootstrap_javascript %}
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Google Shopping Interface</a>
    </div>
      <ul class="nav navbar-nav">
      <li class="divider"></li>
      <li><a href="{% url 'oauth2:index' %}">Update product</a></li>
      <li><a href="{% url 'oauth2:add' %}">Add product</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
          <li class="divider"></li>
          <li><a>Merchant ID: {{ merchant_id }}</a></li>
      </ul>

  </div><!-- /.container-fluid -->
</nav>
<div class="container">
<div class="row">
{% if messages %}
    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
{% endif %}
<div class="col-md-3 col-md-offset-1">
<legend>Update product</legend>
<form method="post" action="">
    {% csrf_token %}
    <div class="form-group">
        <label for="product_id">Product ID</label>
        {{ form.product_id|attr:"class:form-control" }}
    </div>
    <div class="form-group">
        <label for="price">Price</label>
        {{ form.price|attr:"class:form-control" }}
    </div>
    <div class="form-group">
        <label for="currency">Currency</label>
        {{ form.currency|attr:"class:form-control" }}
    </div>
    <div class="form-group">
        <label for="availability">Availability</label>
        {{ form.availability|attr:"class:form-control" }}
    </div>
    <div class="form-group">
        <label for="quantity">Quantity</label>
        {{ form.quantity|attr:"class:form-control" }}
    </div>
    <div class="form-group">
        <button class="btn btn-small btn-success" type="submit">Update product</button>
    </div>
</form>
</div>
<div class="col-md-5 col-md-offset-1">
<legend>Your products</legend>
{% if product_list %}
    <table class="table">
    <td>ID</td>
    <td>Title</td>
    <td>Price</td>

{% for product in product_list %}
    <tr>
    <td>
        {{ product.id }}
    </td>
    <td>
        {{ product.title }}
    </td>
    <td>
        {{ product.price.value }} {{ product.price.currency }}
    </td>

    </tr>
{% endfor %}
    </table>
{% else %}
    <span>You have no products</span>
{% endif %}

</div>
</div>
</div>
<footer class="footer">
      <div class="container">
        <p class="text-muted">Place footer content here.</p>
      </div>
</footer>
</body>
</html>